package com.shinowit.dao.mapper;

import com.shinowit.entity.DeliveryInfo;
import com.shinowit.entity.DeliveryInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int countByExample(DeliveryInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int deleteByExample(DeliveryInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int deleteByPrimaryKey(String deliveryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int insert(DeliveryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int insertSelective(DeliveryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    List<DeliveryInfo> selectByExample(DeliveryInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    DeliveryInfo selectByPrimaryKey(String deliveryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") DeliveryInfo record, @Param("example") DeliveryInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByExample(@Param("record") DeliveryInfo record, @Param("example") DeliveryInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByPrimaryKeySelective(DeliveryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_info
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByPrimaryKey(DeliveryInfo record);

    List<DeliveryInfo> selectPage(DeliveryInfoCriteria example);

    String selectMaxPrimaryKeyValue();
}