package com.shinowit.dao.mapper;

import com.shinowit.entity.MemberSupplyRecord;
import com.shinowit.entity.MemberSupplyRecordCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberSupplyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int countByExample(MemberSupplyRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int deleteByExample(MemberSupplyRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int insert(MemberSupplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int insertSelective(MemberSupplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    List<MemberSupplyRecord> selectByExample(MemberSupplyRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    MemberSupplyRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") MemberSupplyRecord record, @Param("example") MemberSupplyRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int updateByExample(@Param("record") MemberSupplyRecord record, @Param("example") MemberSupplyRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int updateByPrimaryKeySelective(MemberSupplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_supply_record
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    int updateByPrimaryKey(MemberSupplyRecord record);

    List<MemberSupplyRecord> selectPage(MemberSupplyRecordCriteria example);

    Long selectMaxPrimaryKeyValue();
}