package com.shinowit.dao.mapper;

import com.shinowit.entity.OutStock;
import com.shinowit.entity.OutStockCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int countByExample(OutStockCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByExample(OutStockCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByPrimaryKey(Integer outStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insert(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insertSelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    List<OutStock> selectByExample(OutStockCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    OutStock selectByPrimaryKey(Integer outStockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") OutStock record, @Param("example") OutStockCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExample(@Param("record") OutStock record, @Param("example") OutStockCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKeySelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKey(OutStock record);

    List<OutStock> selectPage(OutStockCriteria example);

    Integer selectMaxPrimaryKeyValue();
}