package com.shinowit.dao.mapper;

import com.shinowit.entity.OutStockDetail;
import com.shinowit.entity.OutStockDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutStockDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int countByExample(OutStockDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int deleteByExample(OutStockDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int deleteByPrimaryKey(Integer outStockDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int insert(OutStockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int insertSelective(OutStockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    List<OutStockDetail> selectByExample(OutStockDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    OutStockDetail selectByPrimaryKey(Integer outStockDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") OutStockDetail record, @Param("example") OutStockDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByExample(@Param("record") OutStockDetail record, @Param("example") OutStockDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByPrimaryKeySelective(OutStockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    int updateByPrimaryKey(OutStockDetail record);

    List<OutStockDetail> selectPage(OutStockDetailCriteria example);

    Integer selectMaxPrimaryKeyValue();
}