package com.shinowit.dao.mapper;

import com.shinowit.entity.ProductType;
import com.shinowit.entity.ProductTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTypeMapper {

    List<ProductType> listAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int countByExample(ProductTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByExample(ProductTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByPrimaryKey(String typeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    List<ProductType> selectByExample(ProductTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    ProductType selectByPrimaryKey(String typeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKey(ProductType record);

    List<ProductType> selectPage(ProductTypeCriteria example);

    String selectMaxPrimaryKeyValue();
}