package com.shinowit.dao.mapper;

import com.shinowit.entity.ProductSaleStatus;
import com.shinowit.entity.ProductSaleStatusCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSaleStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int countByExample(ProductSaleStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int deleteByExample(ProductSaleStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int deleteByPrimaryKey(Byte statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int insert(ProductSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int insertSelective(ProductSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    List<ProductSaleStatus> selectByExample(ProductSaleStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    ProductSaleStatus selectByPrimaryKey(Byte statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductSaleStatus record, @Param("example") ProductSaleStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByExample(@Param("record") ProductSaleStatus record, @Param("example") ProductSaleStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByPrimaryKeySelective(ProductSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sale_status
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByPrimaryKey(ProductSaleStatus record);

    List<ProductSaleStatus> selectPage(ProductSaleStatusCriteria example);

    Byte selectMaxPrimaryKeyValue();
}