package com.shinowit.dao.mapper;

import com.shinowit.entity.Provider;
import com.shinowit.entity.ProviderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int countByExample(ProviderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int deleteByExample(ProviderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int deleteByPrimaryKey(String providerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int insert(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int insertSelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    List<Provider> selectByExample(ProviderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    Provider selectByPrimaryKey(String providerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") Provider record, @Param("example") ProviderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByExample(@Param("record") Provider record, @Param("example") ProviderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByPrimaryKeySelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    int updateByPrimaryKey(Provider record);

    List<Provider> selectPage(ProviderCriteria example);

    String selectMaxPrimaryKeyValue();
}