package com.shinowit.dao.mapper;

import com.shinowit.entity.SysLog;
import com.shinowit.entity.SysLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int countByExample(SysLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByExample(SysLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    List<SysLog> selectByExample(SysLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    SysLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysLog record, @Param("example") SysLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByExample(@Param("record") SysLog record, @Param("example") SysLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    int updateByPrimaryKey(SysLog record);

    List<SysLog> selectPage(SysLogCriteria example);

    Integer selectMaxPrimaryKeyValue();
}