package com.shinowit.dao.mapper;

import java.util.List;

import com.shinowit.entity.WebUser;
import com.shinowit.entity.WebUserCriteria;
import org.apache.ibatis.annotations.Param;

public interface WebUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int countByExample(WebUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int deleteByExample(WebUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int insert(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int insertSelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    List<WebUser> selectByExample(WebUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    WebUser selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") WebUser record, @Param("example") WebUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int updateByExample(@Param("record") WebUser record, @Param("example") WebUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int updateByPrimaryKeySelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    int updateByPrimaryKey(WebUser record);

    List<WebUser> selectPage(WebUserCriteria example);

    String selectMaxPrimaryKeyValue();
}