package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Chart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.chart_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private Integer chartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.num
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.price
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.total
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.chart_id
     *
     * @return the value of chart.chart_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public Integer getChartId() {
        return chartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.chart_id
     *
     * @param chartId the value for chart.chart_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setChartId(Integer chartId) {
        this.chartId = chartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.num
     *
     * @return the value of chart.num
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.num
     *
     * @param num the value for chart.num
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.price
     *
     * @return the value of chart.price
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.price
     *
     * @param price the value for chart.price
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.total
     *
     * @return the value of chart.total
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.total
     *
     * @param total the value for chart.total
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chart other = (Chart) that;
        return (this.getChartId() == null ? other.getChartId() == null : this.getChartId().equals(other.getChartId()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChartId() == null) ? 0 : getChartId().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        return result;
    }
}