package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Chart implements Serializable {
    private Product product;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.chart_id
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private Integer chartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.user_name
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.product_code
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.num
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.price
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.total
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.chart_id
     *
     * @return the value of chart.chart_id
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public Integer getChartId() {
        return chartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.chart_id
     *
     * @param chartId the value for chart.chart_id
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setChartId(Integer chartId) {
        this.chartId = chartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.user_name
     *
     * @return the value of chart.user_name
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.user_name
     *
     * @param userName the value for chart.user_name
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.product_code
     *
     * @return the value of chart.product_code
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.product_code
     *
     * @param productCode the value for chart.product_code
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.num
     *
     * @return the value of chart.num
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.num
     *
     * @param num the value for chart.num
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.price
     *
     * @return the value of chart.price
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.price
     *
     * @param price the value for chart.price
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.total
     *
     * @return the value of chart.total
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.total
     *
     * @param total the value for chart.total
     *
     * @mbggenerated Sun Jan 04 16:02:02 CST 2015
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}