package com.shinowit.entity;

import java.io.Serializable;

public class ChartWithBLOBs extends Chart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.user_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private byte[] userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.product_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private byte[] productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.user_name
     *
     * @return the value of chart.user_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public byte[] getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.user_name
     *
     * @param userName the value for chart.user_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setUserName(byte[] userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.product_code
     *
     * @return the value of chart.product_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public byte[] getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.product_code
     *
     * @param productCode the value for chart.product_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setProductCode(byte[] productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChartWithBLOBs other = (ChartWithBLOBs) that;
        return (this.getChartId() == null ? other.getChartId() == null : this.getChartId().equals(other.getChartId()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChartId() == null) ? 0 : getChartId().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        return result;
    }
}