package com.shinowit.entity;

import java.io.Serializable;

public class District implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.id
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.cityId
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.name
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.postCode
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table district
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.id
     *
     * @return the value of district.id
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.id
     *
     * @param id the value for district.id
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.cityId
     *
     * @return the value of district.cityId
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.cityId
     *
     * @param cityid the value for district.cityId
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.name
     *
     * @return the value of district.name
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.name
     *
     * @param name the value for district.name
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.postCode
     *
     * @return the value of district.postCode
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.postCode
     *
     * @param postcode the value for district.postCode
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        District other = (District) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCityid() == null ? other.getCityid() == null : this.getCityid().equals(other.getCityid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPostcode() == null ? other.getPostcode() == null : this.getPostcode().equals(other.getPostcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 05 16:07:39 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCityid() == null) ? 0 : getCityid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPostcode() == null) ? 0 : getPostcode().hashCode());
        return result;
    }
}