package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class InStock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.in_stock_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Integer inStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.provider_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private String providerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.user_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.in_type
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Byte inType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.in_time
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.handler_name
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private String handlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.total_money
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private BigDecimal totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.memo
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_stock
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.in_stock_id
     *
     * @return the value of in_stock.in_stock_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Integer getInStockId() {
        return inStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.in_stock_id
     *
     * @param inStockId the value for in_stock.in_stock_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setInStockId(Integer inStockId) {
        this.inStockId = inStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.provider_code
     *
     * @return the value of in_stock.provider_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public String getProviderCode() {
        return providerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.provider_code
     *
     * @param providerCode the value for in_stock.provider_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode == null ? null : providerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.user_id
     *
     * @return the value of in_stock.user_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.user_id
     *
     * @param userId the value for in_stock.user_id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.in_type
     *
     * @return the value of in_stock.in_type
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Byte getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.in_type
     *
     * @param inType the value for in_stock.in_type
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setInType(Byte inType) {
        this.inType = inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.in_time
     *
     * @return the value of in_stock.in_time
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.in_time
     *
     * @param inTime the value for in_stock.in_time
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.handler_name
     *
     * @return the value of in_stock.handler_name
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.handler_name
     *
     * @param handlerName the value for in_stock.handler_name
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.total_money
     *
     * @return the value of in_stock.total_money
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.total_money
     *
     * @param totalMoney the value for in_stock.total_money
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.memo
     *
     * @return the value of in_stock.memo
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.memo
     *
     * @param memo the value for in_stock.memo
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InStock other = (InStock) that;
        return (this.getInStockId() == null ? other.getInStockId() == null : this.getInStockId().equals(other.getInStockId()))
            && (this.getProviderCode() == null ? other.getProviderCode() == null : this.getProviderCode().equals(other.getProviderCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getInType() == null ? other.getInType() == null : this.getInType().equals(other.getInType()))
            && (this.getInTime() == null ? other.getInTime() == null : this.getInTime().equals(other.getInTime()))
            && (this.getHandlerName() == null ? other.getHandlerName() == null : this.getHandlerName().equals(other.getHandlerName()))
            && (this.getTotalMoney() == null ? other.getTotalMoney() == null : this.getTotalMoney().equals(other.getTotalMoney()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInStockId() == null) ? 0 : getInStockId().hashCode());
        result = prime * result + ((getProviderCode() == null) ? 0 : getProviderCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getInType() == null) ? 0 : getInType().hashCode());
        result = prime * result + ((getInTime() == null) ? 0 : getInTime().hashCode());
        result = prime * result + ((getHandlerName() == null) ? 0 : getHandlerName().hashCode());
        result = prime * result + ((getTotalMoney() == null) ? 0 : getTotalMoney().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}