package com.shinowit.entity;

import java.io.Serializable;

public class MemberAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.user_name
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.recv_man
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String recvMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.tel
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.recv_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String recvAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.post_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_address.default_addr
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private Boolean defaultAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.id
     *
     * @return the value of member_address.id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.id
     *
     * @param id the value for member_address.id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.user_name
     *
     * @return the value of member_address.user_name
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.user_name
     *
     * @param userName the value for member_address.user_name
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.recv_man
     *
     * @return the value of member_address.recv_man
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getRecvMan() {
        return recvMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.recv_man
     *
     * @param recvMan the value for member_address.recv_man
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setRecvMan(String recvMan) {
        this.recvMan = recvMan == null ? null : recvMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.tel
     *
     * @return the value of member_address.tel
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.tel
     *
     * @param tel the value for member_address.tel
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.recv_address
     *
     * @return the value of member_address.recv_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getRecvAddress() {
        return recvAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.recv_address
     *
     * @param recvAddress the value for member_address.recv_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setRecvAddress(String recvAddress) {
        this.recvAddress = recvAddress == null ? null : recvAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.post_code
     *
     * @return the value of member_address.post_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.post_code
     *
     * @param postCode the value for member_address.post_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_address.default_addr
     *
     * @return the value of member_address.default_addr
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public Boolean getDefaultAddr() {
        return defaultAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_address.default_addr
     *
     * @param defaultAddr the value for member_address.default_addr
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setDefaultAddr(Boolean defaultAddr) {
        this.defaultAddr = defaultAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberAddress other = (MemberAddress) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getRecvMan() == null ? other.getRecvMan() == null : this.getRecvMan().equals(other.getRecvMan()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getRecvAddress() == null ? other.getRecvAddress() == null : this.getRecvAddress().equals(other.getRecvAddress()))
            && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
            && (this.getDefaultAddr() == null ? other.getDefaultAddr() == null : this.getDefaultAddr().equals(other.getDefaultAddr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getRecvMan() == null) ? 0 : getRecvMan().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getRecvAddress() == null) ? 0 : getRecvAddress().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getDefaultAddr() == null) ? 0 : getDefaultAddr().hashCode());
        return result;
    }
}