package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderDetail implements Serializable {


    private OrderInfo orderInfo;
    private Product product;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.bill_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private String billCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.num
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.price
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.bill_code
     *
     * @return the value of order_detail.bill_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.bill_code
     *
     * @param billCode the value for order_detail.bill_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_code
     *
     * @return the value of order_detail.product_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_code
     *
     * @param productCode the value for order_detail.product_code
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.num
     *
     * @return the value of order_detail.num
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.num
     *
     * @param num the value for order_detail.num
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.price
     *
     * @return the value of order_detail.price
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.price
     *
     * @param price the value for order_detail.price
     *
     * @mbggenerated Mon Jan 05 09:09:12 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public OrderInfo getOrderInfo() {
        return orderInfo;
    }

    public void setOrderInfo(OrderInfo orderInfo) {
        this.orderInfo = orderInfo;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}