package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class OutStockDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.out_stock_detail_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private Integer outStockDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.out_stock_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private Integer outStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.sell_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.stock_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private BigDecimal stockPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_stock_detail.out_total
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private BigDecimal outTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_stock_detail
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.out_stock_detail_id
     *
     * @return the value of out_stock_detail.out_stock_detail_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public Integer getOutStockDetailId() {
        return outStockDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.out_stock_detail_id
     *
     * @param outStockDetailId the value for out_stock_detail.out_stock_detail_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setOutStockDetailId(Integer outStockDetailId) {
        this.outStockDetailId = outStockDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.product_code
     *
     * @return the value of out_stock_detail.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.product_code
     *
     * @param productCode the value for out_stock_detail.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.out_stock_id
     *
     * @return the value of out_stock_detail.out_stock_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public Integer getOutStockId() {
        return outStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.out_stock_id
     *
     * @param outStockId the value for out_stock_detail.out_stock_id
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setOutStockId(Integer outStockId) {
        this.outStockId = outStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.num
     *
     * @return the value of out_stock_detail.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.num
     *
     * @param num the value for out_stock_detail.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.sell_price
     *
     * @return the value of out_stock_detail.sell_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.sell_price
     *
     * @param sellPrice the value for out_stock_detail.sell_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.stock_price
     *
     * @return the value of out_stock_detail.stock_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public BigDecimal getStockPrice() {
        return stockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.stock_price
     *
     * @param stockPrice the value for out_stock_detail.stock_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setStockPrice(BigDecimal stockPrice) {
        this.stockPrice = stockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_stock_detail.out_total
     *
     * @return the value of out_stock_detail.out_total
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public BigDecimal getOutTotal() {
        return outTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_stock_detail.out_total
     *
     * @param outTotal the value for out_stock_detail.out_total
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setOutTotal(BigDecimal outTotal) {
        this.outTotal = outTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OutStockDetail other = (OutStockDetail) that;
        return (this.getOutStockDetailId() == null ? other.getOutStockDetailId() == null : this.getOutStockDetailId().equals(other.getOutStockDetailId()))
            && (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()))
            && (this.getOutStockId() == null ? other.getOutStockId() == null : this.getOutStockId().equals(other.getOutStockId()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getSellPrice() == null ? other.getSellPrice() == null : this.getSellPrice().equals(other.getSellPrice()))
            && (this.getStockPrice() == null ? other.getStockPrice() == null : this.getStockPrice().equals(other.getStockPrice()))
            && (this.getOutTotal() == null ? other.getOutTotal() == null : this.getOutTotal().equals(other.getOutTotal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock_detail
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOutStockDetailId() == null) ? 0 : getOutStockDetailId().hashCode());
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        result = prime * result + ((getOutStockId() == null) ? 0 : getOutStockId().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getSellPrice() == null) ? 0 : getSellPrice().hashCode());
        result = prime * result + ((getStockPrice() == null) ? 0 : getStockPrice().hashCode());
        result = prime * result + ((getOutTotal() == null) ? 0 : getOutTotal().hashCode());
        return result;
    }
}