package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class ProductStock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_stock.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_stock.avg_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private BigDecimal avgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_stock.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_stock.product_code
     *
     * @return the value of product_stock.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_stock.product_code
     *
     * @param productCode the value for product_stock.product_code
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_stock.avg_price
     *
     * @return the value of product_stock.avg_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public BigDecimal getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_stock.avg_price
     *
     * @param avgPrice the value for product_stock.avg_price
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setAvgPrice(BigDecimal avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_stock.num
     *
     * @return the value of product_stock.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_stock.num
     *
     * @param num the value for product_stock.num
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductStock other = (ProductStock) that;
        return (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()))
            && (this.getAvgPrice() == null ? other.getAvgPrice() == null : this.getAvgPrice().equals(other.getAvgPrice()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Wed Dec 24 16:31:19 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        result = prime * result + ((getAvgPrice() == null) ? 0 : getAvgPrice().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        return result;
    }
}