package com.shinowit.entity;

import java.io.Serializable;

public class Provider implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.provider_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String providerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.provider_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String providerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.provider_name_ab
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String providerNameAb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.address
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.link_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String linkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.link_tel
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String linkTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.qq
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.email
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.sort_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.status
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provider
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.provider_code
     *
     * @return the value of provider.provider_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getProviderCode() {
        return providerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.provider_code
     *
     * @param providerCode the value for provider.provider_code
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode == null ? null : providerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.provider_name
     *
     * @return the value of provider.provider_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.provider_name
     *
     * @param providerName the value for provider.provider_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName == null ? null : providerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.provider_name_ab
     *
     * @return the value of provider.provider_name_ab
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getProviderNameAb() {
        return providerNameAb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.provider_name_ab
     *
     * @param providerNameAb the value for provider.provider_name_ab
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setProviderNameAb(String providerNameAb) {
        this.providerNameAb = providerNameAb == null ? null : providerNameAb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.address
     *
     * @return the value of provider.address
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.address
     *
     * @param address the value for provider.address
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.link_name
     *
     * @return the value of provider.link_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.link_name
     *
     * @param linkName the value for provider.link_name
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.link_tel
     *
     * @return the value of provider.link_tel
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getLinkTel() {
        return linkTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.link_tel
     *
     * @param linkTel the value for provider.link_tel
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel == null ? null : linkTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.qq
     *
     * @return the value of provider.qq
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.qq
     *
     * @param qq the value for provider.qq
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.email
     *
     * @return the value of provider.email
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.email
     *
     * @param email the value for provider.email
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.sort_id
     *
     * @return the value of provider.sort_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.sort_id
     *
     * @param sortId the value for provider.sort_id
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.status
     *
     * @return the value of provider.status
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.status
     *
     * @param status the value for provider.status
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Provider other = (Provider) that;
        return (this.getProviderCode() == null ? other.getProviderCode() == null : this.getProviderCode().equals(other.getProviderCode()))
            && (this.getProviderName() == null ? other.getProviderName() == null : this.getProviderName().equals(other.getProviderName()))
            && (this.getProviderNameAb() == null ? other.getProviderNameAb() == null : this.getProviderNameAb().equals(other.getProviderNameAb()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLinkName() == null ? other.getLinkName() == null : this.getLinkName().equals(other.getLinkName()))
            && (this.getLinkTel() == null ? other.getLinkTel() == null : this.getLinkTel().equals(other.getLinkTel()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getSortId() == null ? other.getSortId() == null : this.getSortId().equals(other.getSortId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider
     *
     * @mbggenerated Tue Dec 30 15:50:09 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProviderCode() == null) ? 0 : getProviderCode().hashCode());
        result = prime * result + ((getProviderName() == null) ? 0 : getProviderName().hashCode());
        result = prime * result + ((getProviderNameAb() == null) ? 0 : getProviderNameAb().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLinkName() == null) ? 0 : getLinkName().hashCode());
        result = prime * result + ((getLinkTel() == null) ? 0 : getLinkTel().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getSortId() == null) ? 0 : getSortId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}