package com.shinowit.entity;

import java.io.Serializable;
import java.util.Date;

public class SysLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.menu_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_time
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.content
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_log
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_id
     *
     * @return the value of sys_log.log_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_id
     *
     * @param logId the value for sys_log.log_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.menu_code
     *
     * @return the value of sys_log.menu_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.menu_code
     *
     * @param menuCode the value for sys_log.menu_code
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_time
     *
     * @return the value of sys_log.log_time
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_time
     *
     * @param logTime the value for sys_log.log_time
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.ip
     *
     * @return the value of sys_log.ip
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.ip
     *
     * @param ip the value for sys_log.ip
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.content
     *
     * @return the value of sys_log.content
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.content
     *
     * @param content the value for sys_log.content
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysLog other = (SysLog) that;
        return (this.getLogId() == null ? other.getLogId() == null : this.getLogId().equals(other.getLogId()))
            && (this.getMenuCode() == null ? other.getMenuCode() == null : this.getMenuCode().equals(other.getMenuCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Mon Jan 05 08:29:27 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogId() == null) ? 0 : getLogId().hashCode());
        result = prime * result + ((getMenuCode() == null) ? 0 : getMenuCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}